name: Deployment
on: workflow_dispatch

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: deploy
        run: echo "Deploying to production" && sleep 60s && echo "Deployment completed"
        shell: bash

